
--
-- DATABASE: `FIXER`
--

CREATE DATABASE fixer;
USE fixer;
-- --------------------------------------------------------

--
-- TABLE STRUCTURE FOR TABLE `DEPARTMENT`
--

CREATE TABLE IF NOT EXISTS `DEPARTMENT` (
  `DEPARTMENT_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(45) NOT NULL,
  `DESCRIPTION` VARCHAR(45) DEFAULT NULL,
  PRIMARY KEY (`DEPARTMENT_ID`)
) ENGINE=INNODB  DEFAULT CHARSET=UTF8 AUTO_INCREMENT=6 ;

--
-- DUMPING DATA FOR TABLE `DEPARTMENT`
--

INSERT INTO `DEPARTMENT` (`DEPARTMENT_ID`, `NAME`, `DESCRIPTION`) VALUES
(2, 'DESIGN', 'DESIGN DEPARTMENT'),
(4, 'ENGINEERING', 'ENGINEERING DEPARTMENT');

-- --------------------------------------------------------
--
-- TABLE STRUCTURE FOR TABLE `EMPLOYEE`
--

CREATE TABLE IF NOT EXISTS `EMPLOYEE` (
  `EMPLOYEE_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(45) NOT NULL,
  `SURNAME` VARCHAR(45) NOT NULL,
  `SALARY` INT(11) NOT NULL,
  `DEPARTMENT_ID` INT(11) DEFAULT NULL,
  PRIMARY KEY (`EMPLOYEE_ID`),
  KEY `FK_EMPLOYEE_DEPARTMENT_IDX` (`DEPARTMENT_ID`)
) ENGINE=INNODB  DEFAULT CHARSET=UTF8 AUTO_INCREMENT=28 ;

--
-- DUMPING DATA FOR TABLE `EMPLOYEE`
--

INSERT INTO `EMPLOYEE` (`EMPLOYEE_ID`, `NAME`, `SURNAME`, `SALARY`, `DEPARTMENT_ID`) VALUES
(25, 'YUKI', 'OZAWA', 7500000, 4),
(26, 'YUSUKE', 'SATO', 8500000, 2);

--
-- CONSTRAINTS FOR TABLE `EMPLOYEE`
--
ALTER TABLE `EMPLOYEE`
  ADD CONSTRAINT `FK_EMPLOYEE_DEPARTMENT` FOREIGN KEY (`DEPARTMENT_ID`) REFERENCES `DEPARTMENT` (`DEPARTMENT_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

